export const DEFAULT_ORDERBOOK_VIEW_DEPTH = 6;
export const DEFAULT_ORDERBOOK_UPDATE_FREQUENCY_IN_MS = 500;
export const PRICE_CHART_MINIMUM_DATA_SAMPLES = 100;
export const OPEN_ORDERS_MINIMUM_PRICE_SPACING = 0.03;