export const DEFAULT_ORDERBOOK_VIEW_DEPTH = 100;
export const DEFAULT_ORDERBOOK_UPDATE_FREQUENCY_IN_MS = 3_000;
export const NUM_ORDERS_VISIBLE_PER_SIDE = 5;
export const PRICE_CHART_DATA_SAMPLES = 100;
export const OPEN_ORDERS_MINIMUM_PRICE_SPACING = 0.05;
export const BID_ASK_SPACING_CHART = 0.1;

export const PRICE_REFRESH_FREQUENCY_IN_MS = 65_000;
export const OPEN_ORDERS_REFRESH_FREQUENCY_IN_MS = 3_000;
export const DOWNTIME_CHECK_FREQUENCY_IN_MS = 1_000;

export const ACTIVE_ORDERS_REFRESH_FREQUENCY_IN_MS = 5_000;
export const CHART_MOVING_AVERAGE_WINDOW_SIZE = 0;

export const STROKE_DASH_ARRAY = 12;

export const MAX_BPS = 10_000;
export const ROOT_PROTOCOL_FEE_BPS = 0;